### ISSUE TITLE
Error when reading textures

### ISSUE THREAD

**Issue by asobolev** [neuroneuro15/wavefront_reader#1]
Seems like there is no option to read textures, the line in the .mtl file like 

`map_Kd img_blobs2_512x512.jpg`

causes an error:

Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/dist-packages/wavefront_reader-0.1.0-py2.7.egg/wavefront_reader/wavefront_reader.py", line 131, in read_wavefront
    materials = read_mtlfile(path.join(path.dirname(fname_obj), fname_mtl))
  File "/usr/local/lib/python2.7/dist-packages/wavefront_reader-0.1.0-py2.7.egg/wavefront_reader/wavefront_reader.py", line 115, in read_mtlfile
    material[prefix] = float(data)
ValueError: could not convert string to float: img_blobs2_512x512.jpg

**Comment by Paandaman** [comment]
I'm getting the same errors.
